### ISSUE TITLE
CLI - MSBuild incorrect "/p:SolutionDir" generated value

### ISSUE THREAD

**Issue by UladzimirMishchanchuk** [bitrise-io/go-xamarin#46]
Hello guys,

I've faced an issue with MSBuild while using Bitrise open source project locally. 
"xamarin-archive" step of my workflow is calling your builder's BuildAllProjects method with MSBuild tool option. The result generated shows incorrect "/p:SolutionDir" parameter value passed to the command. 

According to official docs this value should include the trailing backslash '\'. And my tests show that it does not for now. Here is the [link](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2019) for specs.

Lots of MSBuild targets compose their paths relying on it. Here is an example for [Realm](https://github.com/realm/realm-dotnet/blob/master/NuGet/Realm.Database/Realm.Database.targets) (look at CopyRealmWeaver target).

Please correct this mismatch for running projects using Bitrise and local IDE or MSBuild command.

Thank you.

**Comment by fehersanyi-bitrise** [comment]
Hello @UladzimirMishchanchuk 

Thank you for reporting this issue, I created a task for the tooling team to fix this, they will get back to you when the task is done.

**Comment by UladzimirMishchanchuk** [comment]
@fehersanyi-bitrise, thanks for great tooling

**Comment by lpusok** [comment]
Hi @UladzimirMishchanchuk,
A new version 1.5.2 of xamarin-archive (https://github.com/bitrise-steplib/steps-xamarin-archive/releases/tag/1.5.2) that adds trailing slash to the "/p:SolutionDir"  paramter value is now available.

**Comment by UladzimirMishchanchuk** [comment]
Thanks!
